FROM debian:buster

EXPOSE 9000

RUN apt update -y 

RUN apt install php-fpm php-mysql -y

RUN apt-get install -y php7.3-fpm php7.3-mysql tar

RUN apt install curl -y


COPY ./tools/script.sh /
# COPY ./tools/wp-config.php /

RUN chmod +x /script.sh

CMD [ "/script.sh" ]

# FROM debian:bullseye

# ARG	PHPPATH=/etc/php/7.4/fpm

# RUN apt-get update && apt-get upgrade

# RUN apt-get -y install wget

# RUN apt-get install -y ca-certificates php7.4-fpm php7.4-mysql tar

# RUN	service php7.4-fpm stop

# COPY	conf/www.conf ${PHPPATH}/pool.d/
# RUN		sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' ${PHPPATH}/php.ini && \
# 		sed -i "s/listen = \/run\/php\/php$PHP_VERSION_ENV-fpm.sock/listen = 9000/g" ${PHPPATH}/pool.d/www.conf && \
# 		sed -i 's/;listen.mode = 0660/listen.mode = 0660/g' ${PHPPATH}/pool.d/www.conf && \
# 		sed -i 's/;daemonize = yes/daemonize = no/g' ${PHPPATH}/pool.d/www.conf

# RUN	wget --no-check-certificate https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
# 	chmod +x wp-cli.phar && \
# 	mv wp-cli.phar /usr/local/bin/wp

# RUN	mkdir -p /run/php/ && \
# 	mkdir -p /var/run/php/ && \
# 	mkdir -p /var/www/inception/

# RUN	chown -R www-data:www-data /var/www/inception/

# COPY	conf/wp-config.php /tmp/

# COPY	tools/setup.sh /bin/
# RUN		chmod +x /bin/setup.sh

# CMD		["setup.sh", "php-fpm7.4", "--nodaemonize"]

# RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www

# RUN cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && rm wordpress-6.0-fr_FR.tar.gz

# RUN	chown -R root:root /var/www/wordpress

# RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

# RUN chmod +x wp-cli.phar

# RUN mv wp-cli.phar /usr/local/bin/wp